import PropTypes from 'prop-types';

export const NodePropTypes = PropTypes.shape({
  id: PropTypes.string,
  label: PropTypes.string,

  // Generated by client
  size: PropTypes.number,
  color: PropTypes.string,
});

export const LinkPropTypes = PropTypes.shape({
  source: PropTypes.string,
  target: PropTypes.string,
  weight: PropTypes.number,
  weight_absolute: PropTypes.number,
  strengthen: PropTypes.number,
  weaken: PropTypes.number,
  sign: PropTypes.number,

  // Generated by client
  width: PropTypes.number,
  color: PropTypes.string,
});

export const GraphPropTypes = PropTypes.shape({
  id: PropTypes.number,
  name: PropTypes.string,
  nodes: PropTypes.arrayOf(NodePropTypes),
  links: PropTypes.arrayOf(LinkPropTypes),
});
